#!/usr/bin/with-contenv bash
set -e

# create a catch-all vhost configuration for wordpress
cat > $BITNAMI_APP_DIR/conf/vhosts/wordpress.conf <<EOF
<VirtualHost *:80>
  ServerName localhost
  ServerAlias *

  DirectoryIndex index.html, index.php
  DocumentRoot "$WORDPRESS_INSTALL_DIR"

  <Proxy "fcgi://wordpress-fpm:9000" timeout=300>
  </Proxy>
  <FilesMatch \.php$>
     SetHandler "proxy:fcgi://wordpress-php:9000/"
  </FilesMatch>

  <Directory "$WORDPRESS_INSTALL_DIR">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
EOF
