#!/usr/bin/with-contenv bash

# create a catch-all vhost configuration for wordpress
cat > $BITNAMI_APP_DIR/conf/vhosts/wordpress.conf <<EOF
<VirtualHost *:80>
  ServerName localhost
  ServerAlias *

  DirectoryIndex index.html, index.php
  DocumentRoot "$WORDPRESS_INSTALL_DIR"

  ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://wordpress-php:9000$WORDPRESS_INSTALL_DIR/$1
  <Directory "$WORDPRESS_INSTALL_DIR">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
EOF
