#!/usr/bin/with-contenv bash
set -e

# automatically fetch database parameters from bitnami/mariadb
DATABASE_MASTER_HOST=${DATABASE_MASTER_HOST:-${MARIADB_MASTER_PORT_3306_TCP_ADDR}}
DATABASE_SLAVE_HOST=${DATABASE_SLAVE_HOST:-${MARIADB_SLAVE_PORT_3306_TCP_ADDR}}
DATABASE_SLAVE_HOST=${DATABASE_SLAVE_HOST:-${DATABASE_MASTER_HOST}} # no replication
DATABASE_NAME=${DATABASE_NAME:-${MARIADB_MASTER_ENV_MARIADB_DATABASE}}
DATABASE_USER=${DATABASE_USER:-${MARIADB_MASTER_ENV_MARIADB_USER}}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-${MARIADB_MASTER_ENV_MARIADB_PASSWORD}}

# lookup configurations in the secrets volume
[[ -z ${DATABASE_PASSWORD}    && -f /etc/secrets/database-password ]]     && DATABASE_PASSWORD=$(cat /etc/secrets/database-password)
[[ -z ${AUTH_KEY}             && -f /etc/secrets/auth-key ]]              && AUTH_KEY=$(cat /etc/secrets/auth-key)
[[ -z ${SECURE_AUTH_KEY}      && -f /etc/secrets/secure-auth-key ]]       && SECURE_AUTH_KEY=$(cat /etc/secrets/secure-auth-key)
[[ -z ${LOGGED_IN_KEY}        && -f /etc/secrets/logged-in-key ]]         && LOGGED_IN_KEY=$(cat /etc/secrets/logged-in-key)
[[ -z ${NONCE_KEY}            && -f /etc/secrets/nonce-key ]]             && NONCE_KEY=$(cat /etc/secrets/nonce-key)
[[ -z ${AUTH_SALT}            && -f /etc/secrets/auth-salt ]]             && AUTH_SALT=$(cat /etc/secrets/auth-salt)
[[ -z ${SECURE_AUTH_SALT}     && -f /etc/secrets/secure-auth-salt ]]      && SECURE_AUTH_SALT=$(cat /etc/secrets/secure-auth-salt)
[[ -z ${LOGGED_IN_SALT}       && -f /etc/secrets/logged-in-salt ]]        && LOGGED_IN_SALT=$(cat /etc/secrets/logged-in-salt)
[[ -z ${NONCE_SALT}           && -f /etc/secrets/nonce-salt ]]            && NONCE_SALT=$(cat /etc/secrets/nonce-salt)
[[ -z ${S3_ACCESS_KEY_ID}     && -f /etc/secrets/s3-access-key-id ]]      && S3_ACCESS_KEY_ID=$(cat /etc/secrets/s3-access-key-id)
[[ -z ${S3_SECRET_ACCESS_KEY} && -f /etc/secrets/s3-secret-access-key ]]  && S3_SECRET_ACCESS_KEY=$(cat /etc/secrets/s3-secret-access-key)

if [[ -z ${DATABASE_MASTER_HOST} || -z ${DATABASE_NAME} || -z ${DATABASE_USER} || -z ${DATABASE_PASSWORD} ]]; then
  echo ""
  echo "ERROR: "
  echo "  Please configure the database connection."
  echo "  Cannot continue without a database. Aborting..."
  echo ""
  exit 1
fi

if [[ -z ${S3_ACCESS_KEY_ID}  || -z ${S3_SECRET_ACCESS_KEY} ]]; then
  echo ""
  echo "ERROR: "
  echo "  Please configure the S3 access credentials."
  echo "  Cannot continue. Aborting..."
  echo ""
  exit 1
fi

if [[ -z ${AUTH_KEY}  || -z ${SECURE_AUTH_KEY}  || -z ${LOGGED_IN_KEY}  || -z ${NONCE_KEY} ||
      -z ${AUTH_SALT} || -z ${SECURE_AUTH_SALT} || -z ${LOGGED_IN_SALT} || -z ${NONCE_SALT} ]]; then
  echo ""
  echo "ERROR: "
  echo "  Please configure the salts and keys."
  echo "  Cannot continue. Aborting..."
  echo ""
  exit 1
fi

# configure database settings
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_NAME'\), \+\('database_name_here'\)/\1, '"${DATABASE_NAME}"'/"     $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_USER'\), \+\('username_here'\)/\1, '"${DATABASE_USER}"'/"          $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_PASSWORD'\), \+\('password_here'\)/\1, '"${DATABASE_PASSWORD}"'/"  $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_HOST'\), \+\('localhost'\)/\1, '"${DATABASE_MASTER_HOST}"'/"              $WORDPRESS_INSTALL_DIR/wp-config.php
cat >> $WORDPRESS_INSTALL_DIR/wp-config.php <<EOF
define('DB_SLAVE_HOST', '${DATABASE_SLAVE_HOST}');
EOF

# configure hyperdb
cat > $WORDPRESS_INSTALL_DIR/db-config.php <<EOF
<?php
\$wpdb->save_queries = false;
\$wpdb->persistent = false;
\$wpdb->max_connections = 10;
\$wpdb->check_tcp_responsiveness = true;
\$wpdb->add_database(array(
  'host'     => DB_HOST,
  'user'     => DB_USER,
  'password' => DB_PASSWORD,
  'name'     => DB_NAME,
));
\$wpdb->add_database(array(
  'host'     => DB_SLAVE_HOST,
  'user'     => DB_USER,
  'password' => DB_PASSWORD,
  'name'     => DB_NAME,
  'write'    => 0,
  'read'     => 1,
  'dataset'  => 'global',
  'timeout'  => 0.2,
));
EOF

# configure keys and salt
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('AUTH_KEY'\), \+\('put your unique phrase here'\)/\1, '"${AUTH_KEY}"'/"                  $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('SECURE_AUTH_KEY'\), \+\('put your unique phrase here'\)/\1, '"${SECURE_AUTH_KEY}"'/"    $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('LOGGED_IN_KEY'\), \+\('put your unique phrase here'\)/\1, '"${LOGGED_IN_KEY}"'/"        $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('NONCE_KEY'\), \+\('put your unique phrase here'\)/\1, '"${NONCE_KEY}"'/"                $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('AUTH_SALT'\), \+\('put your unique phrase here'\)/\1, '"${AUTH_SALT}"'/"                $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('SECURE_AUTH_SALT'\), \+\('put your unique phrase here'\)/\1, '"${SECURE_AUTH_SALT}"'/"  $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('LOGGED_IN_SALT'\), \+\('put your unique phrase here'\)/\1, '"${LOGGED_IN_SALT}"'/"      $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('NONCE_SALT'\), \+\('put your unique phrase here'\)/\1, '"${NONCE_SALT}"'/"              $WORDPRESS_INSTALL_DIR/wp-config.php

# unbind wordpress from ip/domain
cat >> $WORDPRESS_INSTALL_DIR/wp-config.php <<EOF
define('WP_HOME', 'http://' . \$_SERVER['HTTP_HOST']);
define('WP_SITEURL', 'http://' . \$_SERVER['HTTP_HOST']);
EOF

# configure S3 access keys
cat >> $WORDPRESS_INSTALL_DIR/wp-config.php <<EOF
define('AWS_ACCESS_KEY_ID', '${S3_ACCESS_KEY_ID}');
define('AWS_SECRET_ACCESS_KEY', '${S3_SECRET_ACCESS_KEY}');
EOF
