#!/usr/bin/with-contenv bash

# automatically fetch database parameters from bitnami/mariadb
DATABASE_HOST=${DATABASE_HOST:-${MARIADB_PORT_3306_TCP_ADDR}}
DATABASE_NAME=${DATABASE_NAME:-${MARIADB_ENV_MARIADB_DATABASE}}
DATABASE_USER=${DATABASE_USER:-${MARIADB_ENV_MARIADB_USER}}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-${MARIADB_ENV_MARIADB_PASSWORD}}

# lookup DATABASE_PASSWORD configuration in secrets volume
if [[ -z ${DATABASE_PASSWORD} && -f /etc/secrets/database-password ]]; then
  DATABASE_PASSWORD=$(cat /etc/secrets/database-password)
fi

if [[ -z ${DATABASE_HOST} || -z ${DATABASE_NAME} || \
      -z ${DATABASE_USER} || -z ${DATABASE_PASSWORD} ]]; then
  echo "ERROR: "
  echo "  Please configure the database connection."
  echo "  Cannot continue without a database. Aborting..."
  exit 1
fi

# configure database settings
s6-setuidgid $BITNAMI_APP_USER cp -a $WORDPRESS_INSTALL_DIR/wp-config-sample.php                                  $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_NAME'\), \+\('database_name_here'\)/\1, '"${DATABASE_NAME}"'/"     $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_USER'\), \+\('username_here'\)/\1, '"${DATABASE_USER}"'/"          $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_PASSWORD'\), \+\('password_here'\)/\1, '"${DATABASE_PASSWORD}"'/"  $WORDPRESS_INSTALL_DIR/wp-config.php
s6-setuidgid $BITNAMI_APP_USER sed -i "s/\('DB_HOST'\), \+\('localhost'\)/\1, '"${DATABASE_HOST}"'/"              $WORDPRESS_INSTALL_DIR/wp-config.php
